//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartments.Resources.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Apartments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Apartments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apartments.Resources.Global.Apartments", typeof(Apartments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated.
        /// </summary>
        public static string _401 {
            get {
                return ResourceManager.GetString("401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized.
        /// </summary>
        public static string _403 {
            get {
                return ResourceManager.GetString("403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page was not found.
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a small company located in {0}. We provide apartment booking services..
        /// </summary>
        public static string about_description {
            get {
                return ResourceManager.GetString("about-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment, no image.
        /// </summary>
        public static string apartment_img_default_alt {
            get {
                return ResourceManager.GetString("apartment-img-default-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string back_to_home {
            get {
                return ResourceManager.GetString("back-to-home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartments.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search apartments.
        /// </summary>
        public static string brand_cta {
            get {
                return ResourceManager.GetString("brand-cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and easy to best service.
        /// </summary>
        public static string brand_description {
            get {
                return ResourceManager.GetString("brand-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make reservation.
        /// </summary>
        public static string btn_reservation {
            get {
                return ResourceManager.GetString("btn-reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review apartment.
        /// </summary>
        public static string btn_review {
            get {
                return ResourceManager.GetString("btn-review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already registered.
        /// </summary>
        public static string confirm_registration_alreadyregistered {
            get {
                return ResourceManager.GetString("confirm-registration-alreadyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration link is not valid.
        /// </summary>
        public static string confirm_registration_notexists {
            get {
                return ResourceManager.GetString("confirm-registration-notexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration link expired.
        /// </summary>
        public static string confirm_registration_timeout {
            get {
                return ResourceManager.GetString("confirm-registration-timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successfull.
        /// </summary>
        public static string confirm_registration_valid {
            get {
                return ResourceManager.GetString("confirm-registration-valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        public static string contact_contact_info {
            get {
                return ResourceManager.GetString("contact-contact-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string delete_profile {
            get {
                return ResourceManager.GetString("delete-profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By deleting profile you will lose access to application..
        /// </summary>
        public static string delete_profile_explanation {
            get {
                return ResourceManager.GetString("delete-profile-explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting profile, try again.
        /// </summary>
        public static string delete_profile_failed {
            get {
                return ResourceManager.GetString("delete-profile-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete profile?.
        /// </summary>
        public static string delete_profile_question {
            get {
                return ResourceManager.GetString("delete-profile-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully deleted profile.
        /// </summary>
        public static string delete_profile_success {
            get {
                return ResourceManager.GetString("delete-profile-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string edit_profile {
            get {
                return ResourceManager.GetString("edit-profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating profile, try again.
        /// </summary>
        public static string edit_profile_failed {
            get {
                return ResourceManager.GetString("edit-profile-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully updated profile.
        /// </summary>
        public static string edit_profile_success {
            get {
                return ResourceManager.GetString("edit-profile-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string label_address {
            get {
                return ResourceManager.GetString("label-address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string label_adults {
            get {
                return ResourceManager.GetString("label-adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string label_children {
            get {
                return ResourceManager.GetString("label-children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string label_city {
            get {
                return ResourceManager.GetString("label-city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string label_date_from {
            get {
                return ResourceManager.GetString("label-date-from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string label_date_to {
            get {
                return ResourceManager.GetString("label-date-to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string label_details {
            get {
                return ResourceManager.GetString("label-details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string label_fname {
            get {
                return ResourceManager.GetString("label-fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string label_lname {
            get {
                return ResourceManager.GetString("label-lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max adults.
        /// </summary>
        public static string label_max_adults {
            get {
                return ResourceManager.GetString("label-max-adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max children.
        /// </summary>
        public static string label_max_children {
            get {
                return ResourceManager.GetString("label-max-children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string label_phone {
            get {
                return ResourceManager.GetString("label-phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string label_sort_by {
            get {
                return ResourceManager.GetString("label-sort-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction.
        /// </summary>
        public static string label_sort_direction {
            get {
                return ResourceManager.GetString("label-sort-direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string label_stars {
            get {
                return ResourceManager.GetString("label-stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total rooms.
        /// </summary>
        public static string label_total_rooms {
            get {
                return ResourceManager.GetString("label-total-rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You inserted invalid combination of Email and password.
        /// </summary>
        public static string login_failed {
            get {
                return ResourceManager.GetString("login-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account?.
        /// </summary>
        public static string login_question {
            get {
                return ResourceManager.GetString("login-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You logged in successfully.
        /// </summary>
        public static string login_success {
            get {
                return ResourceManager.GetString("login-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You logged out successfully.
        /// </summary>
        public static string logout_success {
            get {
                return ResourceManager.GetString("logout-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string option_label_city {
            get {
                return ResourceManager.GetString("option-label-city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sort criteria.
        /// </summary>
        public static string option_label_sort_by {
            get {
                return ResourceManager.GetString("option-label-sort-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1},&lt;br /&gt;&lt;br /&gt;You registered successfully.&lt;br /&gt;Please confirm registration by clicking on link:&lt;br /&gt;&lt;a href=&apos;{2}&apos;&gt;{3}&lt;/a&gt;&lt;br /&gt;.
        /// </summary>
        public static string register_email_body {
            get {
                return ResourceManager.GetString("register-email-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration to Apartments application.
        /// </summary>
        public static string register_email_subject {
            get {
                return ResourceManager.GetString("register-email-subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed, user with inserted username or Email is already registered.
        /// </summary>
        public static string register_failed {
            get {
                return ResourceManager.GetString("register-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        public static string register_question {
            get {
                return ResourceManager.GetString("register-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successfull, confirm registration via Email.
        /// </summary>
        public static string register_success {
            get {
                return ResourceManager.GetString("register-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request reset password.
        /// </summary>
        public static string request_reset_password {
            get {
                return ResourceManager.GetString("request-reset-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message with reset password link will be sent to your Email account..
        /// </summary>
        public static string request_reset_password_description {
            get {
                return ResourceManager.GetString("request-reset-password-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email, reset password Email message was not sent.
        /// </summary>
        public static string request_reset_password_email_invalid {
            get {
                return ResourceManager.GetString("request-reset-password-email-invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or reset password was already sent.
        /// </summary>
        public static string request_reset_password_failed {
            get {
                return ResourceManager.GetString("request-reset-password-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string request_reset_password_question {
            get {
                return ResourceManager.GetString("request-reset-password-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message with instructions for resetting password was sent to inserted Email account.
        /// </summary>
        public static string request_reset_password_success {
            get {
                return ResourceManager.GetString("request-reset-password-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation failed, you have inserted invalid data.
        /// </summary>
        public static string reservation_failed {
            get {
                return ResourceManager.GetString("reservation-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation was successfull.
        /// </summary>
        public static string reservation_success {
            get {
                return ResourceManager.GetString("reservation-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1},&lt;br /&gt;&lt;br /&gt;You have requested to reset password.&lt;br /&gt;Reset your password by clicking on link:&lt;br /&gt;&lt;a href=&apos;{2}&apos;&gt;{3}&lt;/a&gt;&lt;br /&gt;.
        /// </summary>
        public static string reset_password_email_body {
            get {
                return ResourceManager.GetString("reset-password-email-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password in Apartments application.
        /// </summary>
        public static string reset_password_email_subject {
            get {
                return ResourceManager.GetString("reset-password-email-subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while reseting password, try again.
        /// </summary>
        public static string reset_password_failed {
            get {
                return ResourceManager.GetString("reset-password-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully reseted your password.
        /// </summary>
        public static string reset_password_success {
            get {
                return ResourceManager.GetString("reset-password-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment review failed, you have inserted invalid data.
        /// </summary>
        public static string review_failed {
            get {
                return ResourceManager.GetString("review-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more reviews.
        /// </summary>
        public static string review_load_more {
            get {
                return ResourceManager.GetString("review-load-more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to give review.
        /// </summary>
        public static string review_login_first {
            get {
                return ResourceManager.GetString("review-login-first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment review was successfull.
        /// </summary>
        public static string review_success {
            get {
                return ResourceManager.GetString("review-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
    }
}
